# Basic Config
substitutions:
  friendly_name: Washing Machine
  device_name: pow-origin-16a
  slow_update_interval: 10s #this was 90s
  machine_running_delayed_on: 60s  # MINIMUM TIME TO AVOID FALSE POSITIVES, this was 60s
  machine_running_delayed_off: 1min #Was 300s=5min
  minimum_working_time_delayed_on: 30min #this was 30min
  minimum_working_time_delayed_off: 2min #Was 180s=3min
  cycle_centrifughe_delayed_on: 60s   #this was 60s
  cycle_drain_delayed_on: 60s   #this was 60s
  run_elapsed_time_update_interval: 60s
  power_thershold_running: '5' 
  power_thershold_centrifuge_low: '110'
  power_thershold_centrifuge_high: '400'
  power_thershold_drain_low: '15'
  power_thershold_drain_high: '50'
  

esphome:
  name: $device_name

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: $device_name
    password: !secret wifi_failover

captive_portal:

logger:
  level: INFO
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxx"

ota:
  password: !secret ota_pwd

#optional
web_server:
  port: 80

#optional
#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true

#optional
#bluetooth_proxy:
#  active: true

uart:
  - rx_pin: GPIO3
    baud_rate: 4800
    id: dummy_uart  # Will end up being assigned UART0
  - rx_pin: GPIO16
    baud_rate: 4800
    id: active_uart  # Will end up being assigned UART1 to be used for the cse7766 communication

time:
  - platform: homeassistant
    id: homeassistant_time
##################################################################################
##################################################################################
##################################################################################
##################################################################################
globals:
  - id: run_start_epoch
    type: int
    restore_value: no
    initial_value: '-1' 
##################################################################################
##################################################################################
##################################################################################
##################################################################################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: $friendly_name Button
    on_press:
      - switch.toggle: relay_1


################################################################################
#                               Machine running                                #
################################################################################
  - platform: template
    name: RUN
    id: running
    internal: true
  - platform: template
    name: $friendly_name RUN
    id: machine_running
    filters:
      - delayed_on: $machine_running_delayed_on # MINIMUM TIME TO AVOID FALSE POSITIVES, this was 60s
      - delayed_off: $machine_running_delayed_off
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      //} else if ((id(power).state > $power_thershold_running) && !( id(running).state ) ) {
      } else if ((id(power).state > $power_thershold_running)  ) {
        // Running 1st time, let's log        
        //ESP_LOGI("WM.Running","lambda, RUN Cycle Detected, power=%f",id(power).state );
        id(running).publish_state(true);
        return true;
      }
      else if ((id(power).state > $power_thershold_running) ) {
        // Running again
        return true;
      } else {
        // Not running
        return false;
      }
    on_press:
      then: # at cycle start i reset all binary sensors
        - lambda: |-  
            {
              ESP_LOGI("WM.Running","ON Press, Resetting all other cycles to Off. power=%f",id(power).state );
              id(machine_end).publish_state(false);
              id(minimum_working_time).publish_state(false);
              id(cycle_centrifughe).publish_state(false);
              id(cycle_drain).publish_state(false);
              //Current run handling
              if((id(homeassistant_time).now().is_valid()) && (id(run_start_epoch) < 0)){
                ESP_LOGI("WM.Running","ON Press, Storing Current Time in epoch. power=%f",id(power).state );
                auto current_time = id(homeassistant_time).now();
                id(run_start_epoch) = current_time.timestamp;
                ESP_LOGI("WM.Running","ON Press, Storing current power_total_daily=%f",id(power_total_daily).state );
                id(run_power_start).publish_state(id(power_total_daily).state);
              }
              else {
                ESP_LOGI("WM.Running","ON Press, setting epoch to -2. power=%f",id(power).state );
                id(run_start_epoch)= -2;
              }
            }
        - light.turn_on: led
    on_release:
      then: # at the end of cycle turn on end cycle
        - lambda: |-  
            {
              ESP_LOGI("WM.Running","ON Relese, lambda, setting END Cycle to ON. power=%f",id(power).state );
              id(machine_end).publish_state(true);
              //Current run handling
              if(id(run_start_epoch) > 0 ){
                ESP_LOGI("WM.Running","ON Relese, lambda, Storing last run details. power=%f",id(power).state );
                id(run_start_epoch) = -3;
                auto last_run_power = id(power_total_daily).state - id(run_power_start).state;
                ESP_LOGI("WM.Running","ON Relese, lambda, last_run_power=%f",last_run_power );
                std::string lastRunDetails = "Run Finshed ";
                lastRunDetails +=        to_string(id(homeassistant_time).now().hour);
                lastRunDetails += ":" +  to_string(id(homeassistant_time).now().minute);
                lastRunDetails += ", " + to_string(id(homeassistant_time).now().day_of_month);
                lastRunDetails += "/" +  to_string(id(homeassistant_time).now().month);
                lastRunDetails += "/" +  to_string(id(homeassistant_time).now().year);
                lastRunDetails += ", Duration " + id(run_elapsed_time).state;
                lastRunDetails += ", Power Consumed " + to_string(last_run_power) + "kW;
                id(last_run_details).publish_state(lastRunDetails);
                ESP_LOGI("WM.Running","ON Relese, lambda, lastRunDetails published. power=%f",id(power).state );
              }
            }        
################################################################################
#                           Minimum duration cycle                             #
################################################################################
  - platform: template
    name: $friendly_name Minimum time
    internal: true # minimum working time 30m
    id: minimum_working_time 
    filters:
      - delayed_on: $minimum_working_time_delayed_on
      - delayed_off: $minimum_working_time_delayed_off
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > $power_thershold_running) {
        // Running
        return true;
      } else {
        // Not running (the two braces mean it does nothing)
        return {};
      }

################################################################################
#                                Centrifuge                                    #
################################################################################
  - platform: template
    name: CENTRIFUGE
    id: centrifughe
    internal: true
  - platform: template
    name: $friendly_name CENTRIFUGE
    id: cycle_centrifughe
    filters:
      - delayed_on: $cycle_centrifughe_delayed_on
    lambda: |-  
      if (isnan(id(power).state)) {
        ESP_LOGI("WM.Centrifuge","isnan");        
        return {};
      } else if ( (id(power).state > $power_thershold_centrifuge_low)&&(id(power).state < $power_thershold_centrifuge_high)&&(id(minimum_working_time).state) && !(id(centrifughe).state) ){
        //centrifughe for fisrt time, let's log it
        ESP_LOGI("WM.Centrifuge","Centrifuge Cycle Detected, power=%f",id(power).state );
        id(centrifughe).publish_state(true);
        return true;
      } else if ( (id(power).state > $power_thershold_centrifuge_low)&&(id(power).state < $power_thershold_centrifuge_high)&&(id(minimum_working_time).state)  ){
        //centrifughe 
        return true;
      } else {
        // Not running (the two braces mean it does nothing)
        return {};
      }
################################################################################
#                                Water drain                                   #
################################################################################
  - platform: template
    name: DRAIN
    id: drain
    internal: true
  - platform: template
    name: $friendly_name DRAIN
    id: cycle_drain
    filters:
      - delayed_on: $cycle_drain_delayed_on
    lambda: |-  
      if (isnan(id(power).state)) {
        ESP_LOGI("WM.Drain","Drain isnan");
        return {};
      //} else if ( (id(power).state > $power_thershold_drain_low) && (id(power).state < $power_thershold_drain_high) && (id(cycle_centrifughe).state) && ( !(id(drain).state) ) ){
      } else if ( (id(power).state > $power_thershold_drain_low) && (id(power).state < $power_thershold_drain_high) && (id(cycle_centrifughe).state)  ){
        //Draining for fisrt time, let's log it
        //ESP_LOGI("WM.Drain","Drain Detected, power=%f",id(power).state );
        id(drain).publish_state(true);
        return true;
      } else if ( (id(power).state > $power_thershold_drain_low) && (id(power).state < $power_thershold_drain_high) && (id(cycle_centrifughe).state) ){
        //Draining
        return true;
      } else {
        // Not running (the two braces mean it does nothing)
        return {};
      }
    on_press:
      then:
        - lambda: |-
            ESP_LOGI("WM.Drain","on_press, Drain Detected, power=%f",id(power).state );
    on_release:
      then:
        - lambda: |-
            ESP_LOGI("WM.Drain","on_release, Drain set to off, power=%f",id(power).state );
################################################################################
#                                 Machine end                                  #
################################################################################
  - platform: template
    name: $friendly_name END
    id: machine_end
    on_press:
      - light.turn_off: led     
      
################################################################################

switch:
  - platform: gpio
    id: relay_1
    pin: GPIO13
    name: $friendly_name Relay
    restore_mode: ALWAYS_ON
##############################################
output:
  - platform: ledc
    id: pow_blue_led
    pin:
      number: GPIO18
      inverted: True
##############################################
light:
  - platform: monochromatic
    name: $friendly_name Blue LED
    internal: true
    output: pow_blue_led
    id: led
  - platform: status_led
    id: wifi_status_led
    internal: True
    pin:
      number: GPIO05
      inverted: True
##############################################
sensor:
  - platform: wifi_signal
    name: $friendly_name WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: $friendly_name Uptime
  - platform: cse7766
    uart_id: active_uart # Select power meter's UART1
    update_interval: 2s
    current:
      name: $friendly_name Current
      id: curr
      internal: true
    voltage:
      name: $friendly_name Voltage
      id: volt
      internal: true
    power:
      name: $friendly_name Power
      id: power
      internal: true
      on_value_range:
         - above: 4.0
           then:
             - light.turn_on: led
         - below: 3.0
           then:
             - delay: 60s
             - light.turn_off: led
  - platform: total_daily_energy ############################
    name: $friendly_name Total Daily Energy
    power_id: power
    id: power_total_daily
    filters:
        # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    accuracy_decimals: 1      

################################################################################
#                         Slow sensors for Home assistant                      #
################################################################################

  - platform: template #########################
    name: $friendly_name Current
    id: curr_slow
    accuracy_decimals: 3
    lambda: |-
      if (id(curr).state) {
        return (id(curr).state);
      } else {
        return 0;
      }
    unit_of_measurement: A
    icon: "mdi:alpha-a-circle"
    update_interval: $slow_update_interval
  
  - platform: template #########################
    name: $friendly_name Voltage
    id: volt_slow
    lambda: |-
      if (id(volt).state) {
        return (id(volt).state);
      } else {
        return 0;
      }
    unit_of_measurement: V
    icon: "mdi:alpha-v-circle"
    update_interval: $slow_update_interval #this was 90s
  
  - platform: template #########################
    name: $friendly_name Power
    id: power_slow
    lambda: |-
      if (id(power).state) {
        return (id(power).state);
      } else {
        return 0;
      }
    unit_of_measurement: W 
    icon: "mdi:alpha-w-circle"
    update_interval: $slow_update_interval #this was 90s
    
  - platform: template #to hold the power reading when run starts
    id: run_power_start
    internal: true
    unit_of_measurement: W 

  
text_sensor:
  - platform: version
    name: "Sonoff POW ESPHome Version"
##################################################################################
##################################################################################
##################################################################################
##################################################################################

################################################################################
#                               Run Elapsed Time                               #
################################################################################
  - platform: template
    name: "Current Run Elapsed Time"
    id: run_elapsed_time
    update_interval: $run_elapsed_time_update_interval
    lambda: |-
      if ((id(homeassistant_time).now().is_valid()) && (id(run_start_epoch) > 0) && (id(machine_running).state)){
        auto current_time = id(homeassistant_time).now();
        auto time = (current_time.timestamp) - ( id(run_start_epoch)) ;
        auto seconds = ((((int)(time % 60)) < 10)?"0":"") + to_string((int)(time % 60));
        time /= 60;
        auto minutes = ((((int)(time % 60)) < 10)?"0":"") + to_string((int)(time % 60));
        time /= 60;
        auto hours   = ((((int)(time % 60)) < 10)?"0":"") + to_string((int)(time % 60));
        //return hours + ":" + minutes + ":"+seconds;
        return hours + ":" + minutes;
      } else {
        //return {"00:00:00"};
        return {"00:00"};
      }
################################################################################
#                               Last Run Details                               #
################################################################################
  - platform: template
    name: "Last Run Details"
    id: last_run_details
    update_interval: $run_elapsed_time_update_interval

interval:
  - interval: 30s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on: wifi_status_led
        else:
          - light.turn_off: wifi_status_led
